# site settings

title: DRocxk Website
description: Ethical Hacker & CTF Player
taglong: Ethical Hacker & CTF Player
tagshort: Here is my work!
url: https://drocxk.github.io/
baseurl: ""
permalink: pretty
repo: https://github.com/DRocxk/drocxk.github.io

# author settings

author:
  name: John Doe
  email: drocxk@domain.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  facebook: blog
  github: DRocxk
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
